USE [stroke]
GO

CREATE TABLE dbo.PAS (
    spell_id numeric(19,0) PRIMARY KEY,
	S1NHSNumber VARCHAR(10) , 
	S1NoNHSNumber VARCHAR(1),
	S1Surname VARCHAR(30),
	S1Forename VARCHAR(30),
	S1BirthDate DATE,
	S1AgeOnArrival TINYINT,
	S1Gender VARCHAR(1),
	S1PostcodeOut VARCHAR(4),
	S1PostcodeIn VARCHAR(3),
	S1Ethnicity VARCHAR(2),
	S1OnsetInHospital VARCHAR(1),
	S1ArriveByAmbulance VARCHAR(1),
	S1AmbulanceTrust VARCHAR(4),
	S1CadNumber VARCHAR(255),
	S1CadNumberNK VARCHAR(1),
	S1FirstArrivalDateTime DATETIME,
	S1FirstArrivalTimeNotEntered VARCHAR(1),
	S1FirstWard VARCHAR(4),
	S1FirstStrokeUnitArrivalDateTime DATETIME,
	S1FirstStrokeUnitArrivalTimeNotEntered VARCHAR(1),
	S1FirstStrokeUnitArrivalNA VARCHAR(1),
	S2NihssArrival  varchar(2) ,
	S4ArrivalDateTime DATETIME,
	S4ArrivalTimeNotEntered VARCHAR(1),
	S4FirstWard VARCHAR(4),
	S4StrokeUnitArrivalDateTime DATETIME,
	S4StrokeUnitArrivalTimeNotEntered VARCHAR(1),
	S4StrokeUnitArrivalNA VARCHAR(255),
	S7DeathDate DATE,
	S7StrokeUnitDeath VARCHAR(1),
	S7TransferHospitalCode VARCHAR(40),
	S7TransferTeamCode VARCHAR(40),
	S7StrokeUnitDischargeDateTime DATETIME,
	S7StrokeUnitDischargeTimeNotEntered VARCHAR(1),
	S7HospitalDischargeDateTime DATETIME,
	S7HospitalDischargeTimeNotEntered VARCHAR(1),
	S8FollowUp VARCHAR(2),
	S8FollowUpDate DATE,
	S8FollowUpType VARCHAR(2),
	S8FollowUpBy VARCHAR(2),
	S8FollowUpByOther VARCHAR(30),
	S8FollowUpPIConsent VARCHAR(2),
	S8MoodBehaviourCognitiveScreened VARCHAR(2),
	S8MoodBehaviourCognitiveSupportNeeded VARCHAR(1),
	S8MoodBehaviourCognitivePsychologicalSupport VARCHAR(2),
	S8Living VARCHAR(2),
	S8LivingOther VARCHAR(30),
	S8Rankin6Month VARCHAR(1),
	S8PersistentAtrialFibrillation VARCHAR(1),
	S8TakingAntiplateletDrug VARCHAR(1),
	S8TakingAnticoagulent VARCHAR(1),
	S8TakingLipidLowering VARCHAR(1),
	S8TakingAntihypertensive VARCHAR(1),
	S8SinceStrokeAnotherStroke VARCHAR(1),
	S8SinceStrokeMyocardialInfarction VARCHAR(1),
	S8SinceStrokeOtherHospitalisationIllness VARCHAR(1)
)
go