:r ./data/insert_risk_factor_type.sql
:r ./data/insert_comorbidity_type.sql
:r ./data/insert_occupational_therapy_no_assessment_reason_type.sql
:r ./data/insert_observation_type.sql
:r ./data/insert_medication_type.sql
:r ./data/insert_no_continence_plan_reason_type.sql
:r ./data/insert_communication_no_assessment_reason_type.sql
:r ./data/insert_cognitive_status_no_assessment_type.sql
:r ./data/insert_catheter_reason_type.sql
:r ./data/insert_treatment_type.sql
:r ./data/insert_no_swallow_screen_performed_reason_type.sql
:r ./data/insert_swallowing_no_assessment_reason_type.sql
:r ./data/insert_staff_role.sql
:r ./data/insert_rehab_goals_not_set_reason_type.sql
:r ./data/insert_physiotherapy_no_assessment_reason_type.sql
:r ./data/insert_no_scan_reason_type.sql
:r ./data/insert_image_type.sql
:r ./data/insert_diagnosis_type.sql
:r ./data/insert_clinical_classification_type.sql
:r ./data-2/data_inadequate_nutrition_reason_type.sql
:r ./data-2/data_inadequate_fluid_reason_type.sql
:r ./data-2/data_post_discharge_support_type.sql
:r ./data-2/data_post_discharge_therapy_type.sql
:r ./data-2/data_post_discharge_support_type.sql
:r ./data-2/data_comorbidity_type.sql
:r ./data-2/data_level_of_consciousness.sql
:r ./data-2/data_default_mood_assesment_performed.sql
:r ./data-2/data_reasons_not_given.sql
:r ./data-2/data_add_additional_configuration.sql
:r ./data-2/data_default_values.sql
:r ./data-2/data_diagnosis_category_type.sql
:r ./data-2/data_no_swallow_screen_performed_reason_type_2.sql
:r ./data-2/data_post_discharge_support_type.sql
:r ./data-2/data_schemaversion.sql
:r ./data-2/data_ambulance_trust_type.sql
:r ./data-2/data_post_discharge_support_type_2.sql
:r ./data-2/data_pathway_stage.sql
:r ./data-2/data_cimss_user.sql