/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package uk.ac.leeds.lihs.auecr.ssnapexporter.controller;

import java.util.ArrayList;
import java.util.List;
import uk.ac.leeds.lihs.auecr.ssnapexporter.metadata.SsnapField;
import uk.ac.leeds.lihs.auecr.ssnapexporter.metadata.SsnapMetadata;
import uk.ac.leeds.lihs.auecr.ssnapexporter.validation.ValidationRuleSetFactory;
/**
 *
 * @author AjasinA
 */
public class ExpectationFactory {
    
    static SsnapMetadata getExpectationMetadata() {
        
        List<SsnapField> ssnapFieldList = makeSsnapFields();
        SsnapMetadata md = new SsnapMetadata(ssnapFieldList);
        
        return md;
    }
    
    private static List<SsnapField> makeSsnapFields() {
        List<SsnapField> fields = new ArrayList<SsnapField>();
        fields.add(makeSsnapField("1.0", "ImportIdentifier","re:\\w{1,50}"));
        fields.add(makeSsnapField("1.1", "S1HospitalNumber","re:\\w{1,30}"));
        fields.add(makeSsnapField("1.2", "S1NHSNumber","re:\\w{1,10}"));
        fields.add(makeSsnapField("1.2", "S1NoNHSNumber","bool:"));
        fields.add(makeSsnapField("1.3", "S1Surname","re:\\w{1,30}"));
        fields.add(makeSsnapField("1.4", "S1Forename","re:\\w{1,30}"));
        fields.add(makeSsnapField("1.5", "S1BirthDate","date:"));
        fields.add(makeSsnapField("1.5", "S1AgeOnArrival","min:16"));
        fields.add(makeSsnapField("1.6", "S1Gender","re:^(M|F)$"));
        fields.add(makeSsnapField("1.7", "S1PostcodeOut","re:\\w{2,4}"));
        fields.add(makeSsnapField("1.7", "S1PostcodeIn","re:\\w{1,3}"));
        fields.add(makeSsnapField("1.8", "S1Ethnicity","re:^(A|B|C|D|E|F|G|H|I|J|K|L|M|N|P|R|S|Z|99)$"));
        fields.add(makeSsnapField("1.9", "S1Diagnosis","re:^(S|T|O)$"));
        fields.add(makeSsnapField("1.10", "S1OnsetInHospital","yn:"));
        fields.add(makeSsnapField("1.11", "S1OnsetDateTime","dt:"));
        fields.add(makeSsnapField("1.1.0.1", "S1OnsetTimeNotEntered","bool:"));
        fields.add(makeSsnapField("1.11.1", "S1OnsetDateType","re:^(P|BE|DS)$"));
        fields.add(makeSsnapField("1.11.2", "S1OnsetTimeType","re:^(P|BE|NK)$"));
        fields.add(makeSsnapField("1.12", "S1ArriveByAmbulance","yn:"));
        fields.add(makeSsnapField("1.12.1", "S1AmbulanceTrust","re:^(ISA1|ISA2|ISA3|RRU|RX5|RX6|RX7|RX8|RX9|RYA|RYC|RYD|RYE|RYF|WAL|5QT)$"));
        fields.add(makeSsnapField("1.12.2", "S1CadNumber","re:\\w{1,10}"));
        fields.add(makeSsnapField("1.12.3", "S1CadNumberNK","yn:"));
        fields.add(makeSsnapField("1.13", "S1FirstArrivalDateTime","dt:"));
        fields.add(makeSsnapField("1.13.1", "S1FirstArrivalTimeNotEntered","xxx"));
        fields.add(makeSsnapField("1.14", "S1FirstWard","re:^(MAC|SU|ICH|O)$"));
        fields.add(makeSsnapField("1.15", "S1FirstStrokeUnitArrivalDateTime","dt:"));
        fields.add(makeSsnapField("1.15.1", "S1FirstStrokeUnitArrivalTimeNotEntered","yn:"));
        fields.add(makeSsnapField("1.15.2", "S1FirstStrokeUnitArrivalNA","yn:"));
        fields.add(makeSsnapField("2.1.1", "S2CoMCongestiveHeartFailure","yn:"));
        fields.add(makeSsnapField("2.1.2", "S2CoMHypertension","yn:"));
        fields.add(makeSsnapField("2.1.3", "S2CoMAtrialFibrilation","yn:"));
        fields.add(makeSsnapField("2.1.4", "S2CoMDiabetes","yn:"));
        fields.add(makeSsnapField("2.1.5", "S2CoMStrokeTIA","yn:"));
        fields.add(makeSsnapField("2.1.6", "S2CoMAFAntiplatelet","yn::NB"));
        fields.add(makeSsnapField("2.1.7", "S2CoMAFAnticoagulent","yn::NB"));
        fields.add(makeSsnapField("2.2", "S2RankinBeforeStroke","min:0//max:5"));
        fields.add(makeSsnapField("2.3", "S2NihssArrival","min:0//max:42"));
        fields.add(makeSsnapField("2.3.1", "S2NihssArrivalLoc","min:0//max:3"));
        fields.add(makeSsnapField("2.3.2", "S2NihssArrivalLocQuestions","min:-1//max:2"));
        fields.add(makeSsnapField("2.3.3", "S2NihssArrivalLocCommands","min:-1//max:2"));
        fields.add(makeSsnapField("2.3.4", "S2NihssArrivalBestGaze","min:-1//max:2"));
        fields.add(makeSsnapField("2.3.5", "S2NihssArrivalVisual","min:-1//max:3"));
        fields.add(makeSsnapField("2.3.6", "S2NihssArrivalFacialPalsy","min:-1//max:3"));
        fields.add(makeSsnapField("2.3.7", "S2NihssArrivalMotorArmLeft","min:-1//max:4"));
        fields.add(makeSsnapField("2.3.8", "S2NihssArrivalMotorArmRight","min:-1//max:4"));
        fields.add(makeSsnapField("2.3.9", "S2NihssArrivalMotorLegLeft","min:-1//max:4"));
        fields.add(makeSsnapField("2.3.10", "S2NihssArrivalMotorLegRight","min:-1//max:4"));
        fields.add(makeSsnapField("2.3.11", "S2NihssArrivalLimbAtaxia","min:-1//max:2"));
        fields.add(makeSsnapField("2.3.12", "S2NihssArrivalSensory","min:-1//max:2"));
        fields.add(makeSsnapField("2.3.13", "S2NihssArrivalBestLanguage","min:-1//max:3"));
        fields.add(makeSsnapField("2.3.14", "S2NihssArrivalDysarthria","min:-1//max:2"));
        fields.add(makeSsnapField("2.3.15", "S2NihssArrivalExtinctionInattention","min:-1//max:2"));
        fields.add(makeSsnapField("2.4", "S2BrainImagingDateTime","dt:"));
        fields.add(makeSsnapField("2.4.1", "S2BrainImagingTimeNotEntered","bool:"));
        fields.add(makeSsnapField("2.4.2", "S2BrainImagingNotPerformed","bool:"));
        fields.add(makeSsnapField("2.5", "S2StrokeType","re:^(I|PIH)$"));
        fields.add(makeSsnapField("2.6", "S2Thrombolysis","yn:NB"));
        fields.add(makeSsnapField("2.6.1", "S2ThrombolysisNoReason","re:^(TNA|OTSH|USQE|N)$"));
        fields.add(makeSsnapField("2.6.2.1", "S2ThrombolysisNoButHaemorrhagic","bool:"));
        fields.add(makeSsnapField("2.6.2.2", "S2ThrombolysisNoButTimeWindow","bool:"));
        fields.add(makeSsnapField("2.6.2.3", "S2ThrombolysisNoButComorbidity","bool:"));
        fields.add(makeSsnapField("2.6.2.4", "S2ThrombolysisNoButMedication","bool:"));
        fields.add(makeSsnapField("2.6.2.5", "S2ThrombolysisNoButRefusal","bool:"));
        fields.add(makeSsnapField("2.6.2.6", "S2ThrombolysisNoButAge","bool:"));
        fields.add(makeSsnapField("2.6.2.7", "S2ThrombolysisNoButImproving","bool:"));
        fields.add(makeSsnapField("2.6.2.8", "S2ThrombolysisNoButTooMildSevere","bool:"));
        fields.add(makeSsnapField("2.6.2.9", "S2ThrombolysisNoButTimeUnknownWakeUp","bool:"));
        fields.add(makeSsnapField("2.6.2.10", "S2ThrombolysisNoButOtherMedical","bool:"));
        fields.add(makeSsnapField("2.7", "S2ThrombolysisDateTime","jexl:(S2Thrombolysis=~'NB|B')>>dt:"));
        fields.add(makeSsnapField("2.7.1", "S2ThrombolysisTimeNotEntered","bool:"));
        fields.add(makeSsnapField("2.8", "S2ThrombolysisComplications","yn:"));
        fields.add(makeSsnapField("2.8.1.1", "S2ThrombolysisComplicationSih","bool:"));
        fields.add(makeSsnapField("2.8.1.2", "S2ThrombolysisComplicationAO","bool:"));
        fields.add(makeSsnapField("2.8.1.3", "S2ThrombolysisComplicationEB","bool:"));
        fields.add(makeSsnapField("2.8.1.4", "S2ThrombolysisComplicationOther","bool:"));
        fields.add(makeSsnapField("2.8.1", "S2ThrombolysisComplicationOtherDetails","re:\\w{0,30}"));
        fields.add(makeSsnapField("2.9", "S2Nihss24Hrs","jexl:(S2Thrombolysis!~'Y' or (S2Nihss24Hrs>=0&&S2Nihss24Hrs<=42))"));
        fields.add(makeSsnapField("2.9.1", "S2Nihss24HrsNK","bool:"));
        fields.add(makeSsnapField("2.10", "S2SwallowScreening4HrsDateTime","dt:"));
        fields.add(makeSsnapField("2.10.1", "S2SwallowScreening4HrsTimeNotEntered","bool:"));
        fields.add(makeSsnapField("2.10.2", "S2SwallowScreening4HrsNotPerformed","bool:"));
        fields.add(makeSsnapField("2.10.1", "S2SwallowScreening4HrsNotPerformedReason","re:^(OR|PR|PU|NK)$"));
        fields.add(makeSsnapField("2.101", "S2TIAInLastMonth","yn:NK"));
        fields.add(makeSsnapField("2.102", "S2NeurovascularClinicAssessed","jexl:(S2TIAInLastMonth=~'Y' && S2NeurovascularClinicAssessed=~'Y|N') || (S2TIAInLastMonth!~'Y' && empty(S2NeurovascularClinicAssessed))"));
        fields.add(makeSsnapField("2.103", "S2BarthelBeforeStroke","min:0//max:20"));
        fields.add(makeSsnapField("2.104", "S2BrainImagingModality","re:^(CT|MRI|)$"));
        fields.add(makeSsnapField("3.1", "S3PalliativeCare","yn:"));
        fields.add(makeSsnapField("3.1.1", "S3PalliativeCareDecisionDate","jexl:(S3PalliativeCare=~'N'&&empty(S3PalliativeCareDecisionDate))>>date:"));
        fields.add(makeSsnapField("3.1.2", "S3EndOfLifePathway","jexl:(S3PalliativeCare=~'N'&&empty(S3PalliativeCareDecisionDate))>>yn:"));
        fields.add(makeSsnapField("3.2", "S3StrokeNurseAssessedDateTime","jexl:(S3StrokeNurseNotAssessed=~'1'&&empty(S3StrokeNurseAssessedDateTime))>>dt:"));
        fields.add(makeSsnapField("3.2.1", "S3StrokeNurseAssessedTimeNotEntered","bool:"));
        fields.add(makeSsnapField("3.2.2", "S3StrokeNurseNotAssessed","bool:"));
        fields.add(makeSsnapField("3.3", "S3StrokeConsultantAssessedDateTime","jexl:(S3StrokeConsultantNotAssessed=~'1'&&empty(S3StrokeConsultantAssessedDateTime))>>dt:"));
        fields.add(makeSsnapField("3.3.1", "S3StrokeConsultantAssessedTimeNotEntered","bool:"));
        fields.add(makeSsnapField("3.3.2", "S3StrokeConsultantNotAssessed","bool:"));
        fields.add(makeSsnapField("3.4", "S3SwallowScreening72HrsDateTime","dt:"));
        fields.add(makeSsnapField("3.4.0.1", "S3SwallowScreening72HrsTimeNotEntered","bool:"));
        fields.add(makeSsnapField("3.4.0.2", "S3SwallowScreening72HrsNotPerformed","bool:"));
        fields.add(makeSsnapField("3.4.1", "S3SwallowScreening72HrsNotPerformedReason","jexl:(S3SwallowScreening72HrsNotPerformed=~'1'&&empty(S3SwallowScreening72HrsNotPerformedReason))>>re:^(OR|PR|PU|NK)$"));
        fields.add(makeSsnapField("3.5", "S3OccTherapist72HrsDateTime","dt:"));
        fields.add(makeSsnapField("3.5.0.1", "S3OccTherapist72HrsTimeNotEntered","bool:"));
        fields.add(makeSsnapField("3.5.0.2", "S3OccTherapist72HrsNotAssessed","bool:"));
        fields.add(makeSsnapField("3.5.1", "S3OccTherapist72HrsNotAssessedReason","jexl:(S3OccTherapist72HrsNotAssessed=~'1'&&empty(S3OccTherapist72HrsNotAssessedReason))>>re:^(OR|PR|PU|ND|NK)$"));
        fields.add(makeSsnapField("3.6", "S3Physio72HrsDateTime","dt:"));
        fields.add(makeSsnapField("3.6.0.1", "S3Physio72HrsTimeNotEntered","bool:"));
        fields.add(makeSsnapField("3.6.0.2", "S3Physio72HrsNotAssessed","bool:"));
        fields.add(makeSsnapField("3.6.1", "S3Physio72HrsNotAssessedReason","re:^(OR|PR|PU|ND|NK)$"));
        fields.add(makeSsnapField("3.7", "S3SpLangTherapistComm72HrsDateTime","dt:"));
        fields.add(makeSsnapField("3.7.0.1", "S3SpLangTherapistComm72HrsTimeNotEntered","bool:"));
        fields.add(makeSsnapField("3.7.0.2", "S3SpLangTherapistComm72HrsNotAssessed","bool:"));
        fields.add(makeSsnapField("3.7.1", "S3SpLangTherapistComm72HrsNotAssessedReason","re:^(OR|PR|PU|ND|NK)$"));
        fields.add(makeSsnapField("3.8", "S3SpLangTherapistSwallow72HrsDateTime","dt:"));
        fields.add(makeSsnapField("3.8.0.1", "S3SpLangTherapistSwallow72HrsTimeNotEntered","bool:"));
        fields.add(makeSsnapField("3.8.0.2", "S3SpLangTherapistSwallow72HrsNotAssessed","bool:"));
        fields.add(makeSsnapField("3.8.1", "S3SpLangTherapistSwallow72HrsNotAssessedReason","re:^(OR|PR|PS|ND|NK)$"));
        fields.add(makeSsnapField("4.1", "S4ArrivalDateTime","xxx"));
        fields.add(makeSsnapField("4.1.0.1", "S4ArrivalTimeNotEntered","xxx"));
        fields.add(makeSsnapField("4.2", "S4FirstWard","xxx"));
        fields.add(makeSsnapField("4.3", "S4StrokeUnitArrivalDateTime","xxx"));
        fields.add(makeSsnapField("4.3.0.1", "S4StrokeUnitArrivalTimeNotEntered","xxx"));
        fields.add(makeSsnapField("4.3.0.2", "S4StrokeUnitArrivalNA","xxx"));
        fields.add(makeSsnapField("4.4.1", "S4Physio","xxx"));
        fields.add(makeSsnapField("4.5.1", "S4PhysioDays","xxx"));
        fields.add(makeSsnapField("4.6.1", "S4PhysioMinutes","xxx"));
        fields.add(makeSsnapField("4.4.2", "S4OccTher","xxx"));
        fields.add(makeSsnapField("4.5.2", "S4OccTherDays","xxx"));
        fields.add(makeSsnapField("4.6.2", "S4OccTherMinutes","xxx"));
        fields.add(makeSsnapField("4.4.3", "S4SpeechLang","xxx"));
        fields.add(makeSsnapField("4.5.3", "S4SpeechLangDays","xxx"));
        fields.add(makeSsnapField("4.6.3", "S4SpeechLangMinutes","xxx"));
        fields.add(makeSsnapField("4.4.4", "S4Psychology","xxx"));
        fields.add(makeSsnapField("4.5.4", "S4PsychologyDays","xxx"));
        fields.add(makeSsnapField("4.6.4", "S4PsychologyMinutes","xxx"));
        fields.add(makeSsnapField("4.7", "S4RehabGoalsDate","xxx"));
        fields.add(makeSsnapField("4.7.0.1", "S4RehabGoalsNone","xxx"));
        fields.add(makeSsnapField("4.7.1", "S4RehabGoalsNoneReason","xxx"));
        fields.add(makeSsnapField("5.1", "S5LocWorst7Days","xxx"));
        fields.add(makeSsnapField("5.2", "S5UrinaryTractInfection7Days","xxx"));
        fields.add(makeSsnapField("5.3", "S5PneumoniaAntibiotics7Days","xxx"));
        fields.add(makeSsnapField("6.1", "S6OccTherapistByDischargeDateTime","xxx"));
        fields.add(makeSsnapField("6.1.0.1", "S6OccTherapistByDischargeTimeNotEntered","xxx"));
        fields.add(makeSsnapField("6.1.0.2", "S6OccTherapistByDischargeNotAssessed","xxx"));
        fields.add(makeSsnapField("6.1.1", "S6OccTherapistByDischargeNotAssessedReason","xxx"));
        fields.add(makeSsnapField("6.2", "S6PhysioByDischargeDateTime","xxx"));
        fields.add(makeSsnapField("6.2.0.1", "S6PhysioByDischargeTimeNotEntered","xxx"));
        fields.add(makeSsnapField("6.2.0.2", "S6PhysioByDischargeNotAssessed","xxx"));
        fields.add(makeSsnapField("6.2.1", "S6PhysioByDischargeNotAssessedReason","xxx"));
        fields.add(makeSsnapField("6.3", "S6SpLangTherapistCommByDischargeDateTime","xxx"));
        fields.add(makeSsnapField("6.3.0.1", "S6SpLangTherapistCommByDischargeTimeNotEntered","xxx"));
        fields.add(makeSsnapField("6.3.0.2", "S6SpLangTherapistCommByDischargeNotAssessed","xxx"));
        fields.add(makeSsnapField("6.3.1", "S6SpLangTherapistCommByDischargeNotAssessedReason","xxx"));
        fields.add(makeSsnapField("6.4", "S6SpLangTherapistSwallowByDischargeDateTime","xxx"));
        fields.add(makeSsnapField("6.4.0.1", "S6SpLangTherapistSwallowByDischargeTimeNotEntered","xxx"));
        fields.add(makeSsnapField("6.4.0.2", "S6SpLangTherapistSwallowByDischargeNotAssessed","xxx"));
        fields.add(makeSsnapField("6.4.1", "S6SpLangTherapistSwallowByDischargeNotAssessedReason","xxx"));
        fields.add(makeSsnapField("6.5", "S6UrinaryContinencePlanDate","xxx"));
        fields.add(makeSsnapField("6.5.0.1", "S6UrinaryContinencePlanNoPlan","xxx"));
        fields.add(makeSsnapField("6.5.1", "S6UrinaryContinencePlanNoPlanReason","xxx"));
        fields.add(makeSsnapField("6.6", "S6MalnutritionScreening","xxx"));
        fields.add(makeSsnapField("6.6.1", "S6MalnutritionScreeningDietitianDate","jexl:(S6MalnutritionScreening =~ 'N')"));
        fields.add(makeSsnapField("6.6.1.0", "S6MalnutritionScreeningDietitianNotSeen","xxx"));
        fields.add(makeSsnapField("6.7", "S6MoodScreeningDate","xxx"));
        fields.add(makeSsnapField("6.7.0.1", "S6MoodScreeningNoScreening","xxx"));
        fields.add(makeSsnapField("6.7.1", "S6MoodScreeningNoScreeningReason","xxx"));
        fields.add(makeSsnapField("6.8", "S6CognitionScreeningDate","xxx"));
        fields.add(makeSsnapField("6.8.0.1", "S6CognitionScreeningNoScreening","xxx"));
        fields.add(makeSsnapField("6.8.1", "S6CognitionScreeningNoScreeningReason","xxx"));
        fields.add(makeSsnapField("6.9", "S6PalliativeCareByDischarge","xxx"));
        fields.add(makeSsnapField("6.9.1", "S6PalliativeCareByDischargeDate","xxx"));
        fields.add(makeSsnapField("6.9.2", "S6EndOfLifePathwayByDischarge","xxx"));
        fields.add(makeSsnapField("6.10", "S6FirstRehabGoalsDate","xxx"));
        fields.add(makeSsnapField("7.1", "S7DischargeType","xxx"));
        fields.add(makeSsnapField("7.1.1", "S7DeathDate","xxx"));
        fields.add(makeSsnapField("7.1.2", "S7StrokeUnitDeath","xxx"));
        fields.add(makeSsnapField("7.1.3", "S7TransferTeamCode","xxx"));
        fields.add(makeSsnapField("7.2", "S7StrokeUnitDischargeDateTime","xxx"));
        fields.add(makeSsnapField("7.2.0.1", "S7StrokeUnitDischargeTimeNotEntered","xxx"));
        fields.add(makeSsnapField("7.3", "S7HospitalDischargeDateTime","xxx"));
        fields.add(makeSsnapField("7.3.0.1", "S7HospitalDischargeTimeNotEntered","xxx"));
        fields.add(makeSsnapField("7.3.1", "S7EndRehabDate","xxx"));
        fields.add(makeSsnapField("7.4", "S7RankinDischarge","xxx"));
        fields.add(makeSsnapField("7.5", "S7CareHomeDischarge","xxx"));
        fields.add(makeSsnapField("7.5.1", "S7CareHomeDischargeType","xxx"));
        fields.add(makeSsnapField("7.6", "S7HomeDischargeType","xxx"));
        fields.add(makeSsnapField("7.7", "S7DischargedEsdmt","xxx"));
        fields.add(makeSsnapField("7.8", "S7DischargedMcrt","xxx"));
        fields.add(makeSsnapField("7.9", "S7AdlHelp","xxx"));
        fields.add(makeSsnapField("7.9.1", "S7AdlHelpType","xxx"));
        fields.add(makeSsnapField("7.9.2", "S7DischargeVisitsPerWeek","xxx"));
        fields.add(makeSsnapField("7.9.2.0.1", "S7DischargeVisitsPerWeekNK","xxx"));
        fields.add(makeSsnapField("7.10", "S7DischargeAtrialFibrillation","xxx"));
        fields.add(makeSsnapField("7.10.1", "S7DischargeAtrialFibrillationAnticoagulation","xxx"));
        fields.add(makeSsnapField("7.11", "S7DischargeJointCarePlanning","xxx"));
        fields.add(makeSsnapField("7.12", "S7DischargeNamedContact","xxx"));
        fields.add(makeSsnapField("7.101", "S7DischargeBarthel","xxx"));
        fields.add(makeSsnapField("7.102", "S7DischargePIConsent","xxx"));
        fields.add(makeSsnapField("8.1", "S8FollowUp","xxx"));
        fields.add(makeSsnapField("8.1.1", "S8FollowUpDate","xxx"));
        fields.add(makeSsnapField("8.1.2", "S8FollowUpType","xxx"));
        fields.add(makeSsnapField("8.1.3", "S8FollowUpBy","xxx"));
        fields.add(makeSsnapField("8.1.4", "S8FollowUpByOther","xxx"));
        fields.add(makeSsnapField("8.1.5", "S8FollowUpPIConsent","xxx"));
        fields.add(makeSsnapField("8.2", "S8MoodBehaviourCognitiveScreened","xxx"));
        fields.add(makeSsnapField("8.2.1", "S8MoodBehaviourCognitiveSupportNeeded","xxx"));
        fields.add(makeSsnapField("8.2.2", "S8MoodBehaviourCognitivePsychologicalSupport","xxx"));
        fields.add(makeSsnapField("8.3", "S8Living","xxx"));
        fields.add(makeSsnapField("8.3.1", "S8LivingOther","xxx"));
        fields.add(makeSsnapField("8.4", "S8Rankin6Month","xxx"));
        fields.add(makeSsnapField("8.5", "S8PersistentAtrialFibrillation","xxx"));
        fields.add(makeSsnapField("8.6.1", "S8TakingAntiplateletDrug","xxx"));
        fields.add(makeSsnapField("8.6.2", "S8TakingAnticoagulent","xxx"));
        fields.add(makeSsnapField("8.6.3", "S8TakingLipidLowering","xxx"));
        fields.add(makeSsnapField("8.6.4", "S8TakingAntihypertensive","xxx"));
        fields.add(makeSsnapField("8.7.1", "S8SinceStrokeAnotherStroke","xxx"));
        fields.add(makeSsnapField("8.7.2", "S8SinceStrokeMyocardialInfarction","xxx"));
        fields.add(makeSsnapField("8.7.3", "S8SinceStrokeOtherHospitalisationIllness","xxx"));
        return fields;
    }
    
    private static SsnapField makeSsnapField(String number, String name, String ruleSpec) {
        SsnapField field = new SsnapField();
        field.setName(name);
        field.setNumber(number);
        field.setValidationRuleSet(ValidationRuleSetFactory.createRuleSet(ruleSpec));
        
        return field;
    }
}
