ALTER TABLE [dbo].[imaging]  WITH CHECK ADD  CONSTRAINT [FK71F5DB58801C4FC0] FOREIGN KEY([no_scan_reason_id])
REFERENCES [dbo].[no_scan_reason_type] ([id])
GO

ALTER TABLE [dbo].[imaging] CHECK CONSTRAINT [FK71F5DB58801C4FC0]
GO

ALTER TABLE [dbo].[imaging]  WITH CHECK ADD  CONSTRAINT [FK71F5DB58AB97EDDC] FOREIGN KEY([scan_id])
REFERENCES [dbo].[scan] ([id])
GO

ALTER TABLE [dbo].[imaging] CHECK CONSTRAINT [FK71F5DB58AB97EDDC]
GO