ALTER TABLE [dbo].[scan]  WITH CHECK ADD  CONSTRAINT [FK35C67D67AAE64B] FOREIGN KEY([diagnosis_type_id])
REFERENCES [dbo].[diagnosis_type] ([id])
GO

ALTER TABLE [dbo].[scan] CHECK CONSTRAINT [FK35C67D67AAE64B]
GO

ALTER TABLE [dbo].[scan]  WITH CHECK ADD  CONSTRAINT [FK35C67D7E1B8B1F] FOREIGN KEY([image_type_id])
REFERENCES [dbo].[image_type] ([id])
GO

ALTER TABLE [dbo].[scan] CHECK CONSTRAINT [FK35C67D7E1B8B1F]
GO


