ALTER TABLE [dbo].[treatment]  WITH CHECK ADD  CONSTRAINT [FKFC397878C11D709F] FOREIGN KEY([care_activity_id])
REFERENCES [dbo].[care_activity] ([id])
GO

ALTER TABLE [dbo].[treatment] CHECK CONSTRAINT [FKFC397878C11D709F]
GO

ALTER TABLE [dbo].[treatment]  WITH CHECK ADD  CONSTRAINT [FKFC397878FAC0C7A0] FOREIGN KEY([type_id])
REFERENCES [dbo].[treatment_type] ([id])
GO

ALTER TABLE [dbo].[treatment] CHECK CONSTRAINT [FKFC397878FAC0C7A0]
GO
